# Generated by Django 4.0.6 on 2022-09-04 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0003_alter_preferences_id'),
        ('SiteView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='email', help_text='how do you name this method? email or github or anything else?', max_length=1024)),
                ('link', models.URLField(default='example@gmail.com', help_text='the link of your contact method.', max_length=1024)),
                ('icon', models.CharField(default='email', help_text='for display on front page, use the icon name from this page: https://semantic-ui.com/elements/icon.html', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MyTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='student', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('my_name', models.CharField(default='me', help_text='your name.', max_length=1024)),
                ('my_brief_intro', mdeditor.fields.MDTextField(default='I am a student.', help_text='self introduction on front page.', max_length=1024)),
                ('my_photo', imagekit.models.fields.ProcessedImageField(default='avatar2/matthew.png', upload_to='avatar2', verbose_name='photo')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='www.google.com', max_length=1024)),
            ],
        ),
    ]
