# Generated by Django 4.0.6 on 2022-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteView', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='email', help_text='how do you name this method? email or github or anything else?', max_length=1024)),
                ('link', models.URLField(default='example@gmail.com', help_text='the link of your contact method.', max_length=1024)),
                ('icon', models.CharField(default='email', help_text='for display on front page, use the icon name from this page: https://semantic-ui.com/elements/icon.html', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MyTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='student', max_length=1024)),
            ],
        ),
    ]
