# Generated by Django 4.0.6 on 2022-08-31 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteView', '0002_initial'),
        ('preferences', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('my_name', models.CharField(default='me', help_text='your name.', max_length=1024)),
                ('my_brief_intro', mdeditor.fields.MDTextField(default='I am a student.', help_text='self introduction on front page.', max_length=1024)),
                ('my_photo', imagekit.models.fields.ProcessedImageField(default='avatar2/matthew.png', upload_to='avatar2', verbose_name='photo')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
