# Generated by Django 4.1 on 2022-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulication',
            name='Name',
            field=models.CharField(max_length=1024),
        ),
    ]
