# Generated by Django 4.1 on 2022-08-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0003_rename_name_pulication_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulication',
            old_name='name',
            new_name='Name',
        ),
    ]
